### ISSUE TITLE
TypeError: Attempted to load JSON module without specifying "type": "json" attribute in the import statement.

### ISSUE THREAD

**Issue by moshpirit** [jmbuhr/quarto-nvim-kickstarter#131]
Hello, I'm trying to preview a quarto file, but I've encountered this error. This is my first time using quarto. I've followed the steps in [this video](https://www.youtube.com/watch?v=3sj7clNowlA) 

```
ERROR: TypeError: Attempted to load JSON module without specifying "type": "json" attribute in the import statement.

Stack trace:
    at async initYamlIntelligenceResourcesFromFilesystem (file:///usr/lib/quarto-cli/bin/quarto.js:82343:29)
    at async file:///usr/lib/quarto-cli/bin/quarto.js:78761:9
    at async initState (file:///usr/lib/quarto-cli/bin/quarto.js:78769:5)
    at async Command.actionHandler (file:///usr/lib/quarto-cli/bin/quarto.js:100593:5)
    at async Command.execute (file:///usr/lib/quarto-cli/bin/quarto.js:8017:13)
    at async Command.parseCommand (file:///usr/lib/quarto-cli/bin/quarto.js:7907:20)
    at async quarto (file:///usr/lib/quarto-cli/bin/quarto.js:118207:9)
    at async file:///usr/lib/quarto-cli/bin/quarto.js:118227:9
    at async mainRunner (file:///usr/lib/quarto-cli/bin/quarto.js:118111:9)
    at async file:///usr/lib/quarto-cli/bin/quarto.js:118218:5

[Process exited 1]
```
I've tried it out with [this example too](https://quarto.org/docs/get-started/hello/neovim.html#render-and-preview), and I'm getting the same result :(    

BTW, Mason doesn't seem to install `◍ bash-language-server`. Not sure if  I should do anything about it or if that's even related to this issue (I'm just a newbie with nvim).

**Comment by jmbuhr** [comment]
Looks like an error coming from quarto itself, not Neovim, so the issue is better suited for https://github.com/quarto-dev/quarto-cli.

**Comment by moshpirit** [comment]
Sorry! I'll search there! Thanks for the response! :)
